### ISSUE TITLE
Bug - getting error 

### ISSUE THREAD

**Issue by ramblerswebs** [luncheon/clocklet#10]
When I look at the console in my browser I see this error message on clocklet.min.js 1:30518
 'matches' called on an object that does not implement interface Element.

I also get this same message on Pause on Exception when I try and debug my own code.

**Comment by luncheon** [comment]
@ramblerswebs  
Right! Thank you! I will fix it.

**Comment by luncheon** [comment]
Fixed in v0.2.6.

**Comment by ramblerswebs** [comment]
thanks - that seems to have fixed the problem
