### ISSUE TITLE
Feature: auto close when minutes are selected 

### ISSUE THREAD

**Issue by yaitskov** [luncheon/clocklet#2]
The widget is very simple. 99% popup should be closed after user clicks minutes.

**Comment by luncheon** [comment]
I think you can do that with the following code:

```javascript
window.addEventListener('click', function (event) {
  if (event.target.classList.contains('clocklet-tick--minute')) {
    clocklet.close();
  }
});
```

How is it?

**Comment by luncheon** [comment]
(But how do you make the users aware of that behavior? I think that behavior may not be guessed from the appearance.)
