### ISSUE TITLE
Load

### ISSUE THREAD

**Issue by shaan1974** [luncheon/clocklet#5]
Hello,

Is it normal that the js should place after the body definition to work properly ?

If i put it before i got an error.

Best regards
Shaan

**Comment by luncheon** [comment]
Hi, @shaan1974.

The demo page places the `<script>` inside of the `<body>` and seems to work.  
https://luncheon.github.io/clocklet/demo.html

Could you please tell me more about the error?

1. Error message
2. OS / browser
3. HTML structure

**Comment by shaan1974** [comment]
If you put the script tag before the body tag, is not working because in the code you attach an event to the body tag.

in the min version :

 document.body.addEventListener("focus", function(t) {
                var e = t.target;
                c(e) && o.open(e, n(e))
            }, !0),

So if you set the script tag before the body tag it crash.

By the way nice piece of code. I use it for one of my component in my vue form generator.

**Comment by luncheon** [comment]
OK, thank you!  
I'll bind the event to `window` instead of `document.body`.

**Comment by luncheon** [comment]
v0.2.5 is published and this issue should be fixed.

**Comment by shaan1974** [comment]
Ok thanks.
