### ISSUE TITLE
Not rendering the clocklet

### ISSUE THREAD

**Issue by SterlingButters** [luncheon/clocklet#6]
Greetings, I would really like to use this clocklet in my application. I can't seem to get the clock to render though - see codepen: https://codepen.io/sterlingbutters/pen/yLNQJbm?editors=1111

**Comment by luncheon** [comment]
Hi, @SterlingButters.

Thank you. README was wrong.  

```
<link rel="https://cdn.jsdelivr.net/npm/clocklet@0.2.4/css/clocklet.min.css">
```

Please specify the following instead of the above:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/clocklet@0.2.4/css/clocklet.min.css">
```

**Comment by SterlingButters** [comment]
@luncheon Perfect - its beautiful
