### ISSUE TITLE
Guidance for modal UI (z-index appears different between input and clocklet)

### ISSUE THREAD

**Issue by SterlingButters** [luncheon/clocklet#7]
Greetings,
1) See example here: https://codepen.io/sterlingbutters/pen/BaNqVPJ?editors=0001 
2) Click on the circle without the "+" 
3) Click clocklet input
4) Observe clocklet behind modal
How can I get this in the modal window?

**Comment by luncheon** [comment]
clocklet has `z-index` option.  
https://github.com/luncheon/clocklet#available-options

```html
<input data-clocket="z-index: 1050;">
```

Or, `append-to` option can also be used.

```html
<input data-clocket="append-to: parent;">
```

**Comment by SterlingButters** [comment]
Awesome, thanks for such quick responses
