### ISSUE TITLE
Clock Visible by Default

### ISSUE THREAD

**Issue by SterlingButters** [luncheon/clocklet#8]
Is is possible for the clock to be visible by default without clicking the input first?

**Comment by luncheon** [comment]
It's an unexpected use but it can be done with a little hack.

```js
const inputElement = document.getElementById('input');
new clocklet.constructor().open(inputElement);
```

However, since the clock has `absolute` position, it is necessary to be cared about spaces.

Example: 
https://codepen.io/luncheon/pen/oNXRRxZ

**Comment by SterlingButters** [comment]
@luncheon perfect, (I could probably do without this next part if it isn’t possible but...) can you also hide the input field to only show the clock?

**Comment by luncheon** [comment]
@SterlingButters  
clocklet requires `input` element.  That can have `hidden` attribute and/or `display: none` style.

**Comment by SterlingButters** [comment]
@luncheon perfect that works, thanks for such quick responses!
